### ISSUE TITLE
Corrected Resources (RU and UK)

### ISSUE THREAD

**Issue by InfDev** [LazZiya/ExpressLocalizationSample#6]
Corrected Resources:
ExpressLocalizationResource.ru.resx
ExpressLocalizationResource.uk.resx
ViewLocalizationResource.ru.resx
ViewLocalizationResource.uk.resx

[LocResx_RU_and_UK.zip](https://github.com/LazZiya/ExpressLocalizationSample/files/3662826/LocResx_RU_and_UK.zip)

**Comment by LazZiya** [comment]
@InfDev many thanks for your efforts, I will add the files soon.

**Comment by LazZiya** [comment]
fixed in commit https://github.com/LazZiya/ExpressLocalizationSample/commit/861010eb850f5e24218968344c5236a04264591f 
thanks :)
