### ISSUE TITLE
Date in ExpressLocalizationResource.fr.resx

### ISSUE THREAD

**Issue by werddomain** [LazZiya/ExpressLocalizationSample#7]
The date value in this field is set to 'Rendez-vous amoureux'. This in french meen like 'Your love date' Like if your are dating some one. The correct value is simply **Date**.

**Comment by LazZiya** [comment]
@werddomain thanks for the correction, I will fix it soon.
may be I should warn google translate as well :)

**Comment by LazZiya** [comment]
fixed in commit https://github.com/LazZiya/ExpressLocalizationSample/commit/861010eb850f5e24218968344c5236a04264591f 
thanks :)
